### ISSUE TITLE
[Docs] Swagger Autogen 커스텀 페이징 응답 오류

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#101]
## ❌ Bug explanation

> 버그가 발생한 상황을 설명해주세요.

Swagger-Autogen 파싱 과정에서 PageAble 객체에 대한 응답이 아래와 같이 기술됩니다.
`sort` 필드는 실제 응답에서 Array로 출력되므로, parsing error가 발생합니다.

- Swagger description (`SortObject`)
<img src="https://github.com/user-attachments/assets/1392bfb9-5a45-4b27-8b23-2989e90cad58" alt="이미지 설명" width="300" height="300"> 

```yaml
"SortObject": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "sorted": {
              "type": "string"
            },
            "unsorted": {
              "type": "string"
            },
            "empty": {
              "type": "string"
            }
          }
        }
      }
```

- Web response
```json
{
    "timestamp": "2024-08-18T01:04:23.070415",
    "httpStatus": 200,
    "code": "NOF-2002",
    "message": "회원의 가입된 조직 조회에 성공하였습니다.",
    "data": {
        "content": [
            {
                "role": "LEADER",
                "organizationId": 4,
                "organizationName": "loveysuby",
                "profileImage": "null"
            }
        ],
        "pageable": {
            "pageNumber": 0,
            "pageSize": 5,
            "sort": [], // expected case
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "first": true,
        "last": true,
        "size": 5,
        "number": 0,
        "sort": [], // expected case
        "numberOfElements": 3,
        "empty": false
    }
}
```

## 🐞 Location of Occurrence

> 버그가 발생된 로그 혹은 코드 위치를 적어주세요.
OperationId : `getJoined`

## 📚 Remarks
-
